# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c7d845dc4b270cf891de24423933f8ef8437d636ba13c2028921b545552031289dc5cb6efdf5f1f95d8aeccadb9d20063c0dc8ed74c5e96fa629a63db9ec444

test:
  secret_key_base: 223fb40fb4da67be3b5ce0f48f238e90075039f4a7d66f0a72d341a3056059927f4b1fc2459be37c5a5e29c874543f20580c49c711270235fce5e5506a43eadc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
